# Generated by Django 4.2.4 on 2024-05-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biblioteca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "direccion",
                    models.CharField(
                        help_text="Debe contener un número al final", max_length=200
                    ),
                ),
                ("ciudad", models.CharField(max_length=100)),
                ("horario_apertura", models.TimeField()),
                ("horario_cierre", models.TimeField()),
                ("fecha_fundacion", models.DateField()),
                (
                    "normas",
                    models.FileField(blank=True, null=True, upload_to="normas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("sinopsis", models.TextField()),
                ("anio_publicacion", models.DateField()),
                ("editorial", models.CharField(max_length=100)),
                (
                    "isbn",
                    models.CharField(help_text="Formato: 0-7645-2641-3", max_length=17),
                ),
                ("num_ejemplares", models.IntegerField()),
                (
                    "biblioteca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.biblioteca",
                    ),
                ),
            ],
        ),
    ]
